services:
  - type: web
    name: studysafe-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    autoDeploy: true
    envVars:
      - key: PORT
        value: 10000
      - key: DB_HOST
        value: your_mysql_host
      - key: DB_USER
        value: your_mysql_user
      - key: DB_PASSWORD
        value: your_mysql_password
      - key: DB_NAME
        value: studysafe
      - key: JWT_SECRET
        value: your_jwt_secret
